# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20171024_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='nickname', max_length=20, verbose_name='닉네임'),
            preserve_default=False,
        ),
    ]
